import { flexbox } from "@chakra-ui/react";

const buttonStyles = {
  baseStyle: {
    my: "1",
    display: "flex",
    alignSelf: "flex-start",
    bg: "transparent",
    borderColor: "gray.600",
    color: "gray.600",
  },
  sizes: {},
  variants: {
    base: {},
    navActive: {
      px: "0",
      pr: "6",
      py: "0",
      mx: "4",
      w: "auto",
      fontSize: "18px",
      display: "block",
      color: "white",
      fontWeight: "700",
      letterSpacing: "1px",
      borderBottom: "2px solid",
      borderRadius: "0",
      borderBottomColor: "blue.100",
      transition: "all .2s ease-in-out",
    },
    nav: {
      px: "4",
      py: "0",
      m: "0",
      w: "auto",
      fontSize: "18px",
      display: "block",
      color: "gray.200",
      fontWeight: "600",
      letterSpacing: "1px",
      borderBottom: "2px solid",
      borderRadius: "0",
      borderBottomColor: "transparent",
      transition: "all .1s ease-in-out .1s",
    },
    inputElement: {
      display: "flex",
      justify: "center",
      fontSize: "20px",
      pt: "3px",
      bg: "none",
      color: "gray.500",
      display: "inline",
      lineHeight: "inherit",
      m: "0",

      _hover: {
        color: "gray.800",
        transform: "scale(1.05)",
      },
    },
    photoSection: {
      border: "1px solid",
      borderColor: "blue.400",
      color: "blue.400",
      bg: "gray.50",
      p: "2",
      _hover: {
        bg: "blue.50",
      },
    },
    deleteSaved: {
      border: "1px solid",
      borderColor: "gray.400",
      color: "gray.500",
      bg: "gray.50",
      p: "0",
      m: "0",
      h: "30px",
      w: "30px",
      minW: "0",
      fontSize: "14px",
      _hover: {
        bg: "red.50",
        color: "red.400",
        borderColor: "red.400",
      },
    },
    save: {
      width: "100%",
      bg: "green.400",
      color: "white",
      _disabled: {
        border: "1px solid",
        borderColor: "gray.600",
        color: "gray.600",
        bg: "transparent",
        _hover: {
          color: "gray.600",
        },
      },
      _hover: {
        bg: "green.500",
        color: "gray.50",
      },
    },
    add: {
      width: "100%",
      bg: "blue.400",
      color: "white",
      _hover: {
        bg: "blue.500",
        color: "gray.50",
      },
    },
  },
  defaultProps: { padding: "2" },
};
export { buttonStyles };
